name: Build Android APK

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.24.0'

    - name: Install Python Dependencies
      run: |
        pip install --upgrade pip
        pip install -r requirements.txt

    - name: Create .env file
      run: |
        echo "SUPABASE_URL=${{ secrets.SUPABASE_URL }}" >> .env
        echo "SUPABASE_KEY=${{ secrets.SUPABASE_KEY }}" >> .env
        echo "YOUTUBE_CHANNEL_ID=${{ secrets.YOUTUBE_CHANNEL_ID }}" >> .env

    # CORREÇÃO AQUI: Trocado --project-name por --product-name
    - name: Build APK
      run: |
        flet build apk --module-name app --org "com.ieq.araraquara"

    - name: Upload APK Artifact
      uses: actions/upload-artifact@v4
      with:
        name: IEQ-Araraquara-APK
        path: build/apk/*.apk
